name: lint-and-test

on: push


jobs:
  check:
    runs-on: ubuntu-latest
    name: "Check (on Python3.11)"
    steps:
      - uses: actions/setup-python@d09bd5e6005b175076f227b13d9730d56e9dcfcb
        with:
          python-version: 3.12
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          version: "0.9.22"
          enable-cache: true
      - uses: actions/checkout@v3
      - uses: pre-commit/action@646c83fcd040023954eafda54b4db0192ce70507

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install uv and set Python version
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          version: "0.9.22"
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - id: install_dependencies
        run: uv sync --locked --all-extras --dev

      - id: run_tests
        run: uv run pytest --cov . --cov-report xml

      - name: Upload test coverage xml as artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: coverage-results-${{ matrix.python-version }}
          path: coverage.xml
